### ISSUE TITLE
Burgerstation 13 seems to be incorrectly listed as a downstream of Citadel

### ISSUE THREAD

**Issue by pitaden** [CthulhuOnIce/SS13-Codebases#15]
Burgerstation is built from scratch, and isn't a fork of any server.

**Comment by ZeWaka** [comment]
You probably want https://github.com/spacestation13/SS13-Codebases

**Comment by pitaden** [comment]
oh no! didn't realize this wasn't the latest version! looks like it's been fixed

**Comment by CthulhuOnIce** [comment]
I'll still fix it here
